### What is NumPy?
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.



### Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



### How to install of NumPy package ?
- !pip install numpy

In [ ]:
!pip install numpy

### How to Import NumPy Package ?
- import numpy as np

In [4]:
import numpy as np

### How to Cheack Numpy Version ?

In [16]:
np.__version__

'2.0.1'

### How to Create NumPy array ?

In [7]:
arr1 = np.array([11, 23, 32, 41, 57])
arr1

[1 2 3 4 5]


In [8]:
arr2 = np.array([11, 23, 32, 41, 57])
arr2

array([11, 23, 32, 41, 57])

In [11]:
arr3 = np.array(['a','b','c','d','e'])
arr3

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

### How to Check datatype of Numpy Object ?

In [12]:
arr1 = np.array([11, 23, 32, 41, 57])
arr1

array([11, 23, 32, 41, 57])

In [13]:
type(arr1)

numpy.ndarray