## NumPy ufuncs

### What are ufuncs?
- ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

### Why use ufuncs?
- ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
- They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
- ufuncs also take additional arguments, like:
   1) where boolean array or condition defining where the operations should take place.
   2) dtype defining the return type of elements.
   3) out output array where the return value should be copied.

### What is Vectorization?
- Converting iterative statements into a vector based operation is called vectorization.
- It is faster as modern CPUs are optimized for such operations.

## Simple Arithmetic

In [3]:
import numpy as np

#### 1. Addition of Array

In [12]:
# Add the values in arr1 to the values in arr2:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


#### 2. Subtraction of Array

In [ ]:
# Subtract the values in arr2 from the values in arr1:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

#### 3. Multiplication

In [ ]:
# Multiply the values in arr1 with the values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)

#### 4. Dot Product

In [10]:
# Multiply the values in arr1 with the values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.dot(arr1, arr2)
print(newarr)

4900


#### 5. Division

In [ ]:
# Divide the values in arr1 with the values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)

#### 6. Exponentiation between array

In [ ]:
# Raise the valules in arr1 to the power of values in arr2:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)

#### 7. Remainder

In [ ]:
# Return the remainders:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

#### 8. Quation and Remainder

In [ ]:
# Return the quotient and mod:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)

## Advance Arithmatic

#### 1.Exponentiation

In [5]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
newarr = np.square(arr1)
print(newarr)

[ 100  400  900 1600 2500 3600]


In [6]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
newarr = np.power(arr1, 3)
print(newarr)

[  1000   8000  27000  64000 125000 216000]


In [8]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
newarr = np.power(arr1, 5)
print(newarr)

[   100000   3200000  24300000 102400000 312500000 777600000]


#### 2.Logarithm

In [19]:
# Find log at base 2 of all elements of following array:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.log2(arr))

[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619 5.9068906 ]


In [20]:
# Find log at base 10 of all elements of following array:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.log10(arr))

[1.         1.30103    1.47712125 1.60205999 1.69897    1.77815125]


In [21]:
# Find log at base e of all elements of following array:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.log(arr))

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456]


In [23]:
# Find log at base 15 of all elements of following array:
arr = np.array([10, 20, 30, 40, 50, 60])
newarr = np.log(arr) / np.log(15)
print(newarr)

array([0.85027415, 1.10623218, 1.25595802, 1.3621902 , 1.44459028,
       1.51191605])

#### 3.LCM Lowest Common Multiple

In [30]:
# Find the LCM of the following two numbers:
num1 = 4
num2 = 6
arr = np.array([4, 6])
x = np.lcm(num1,num2)
print(x)

12


In [31]:
# Find the LCM of the values of the following array:
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


#### 4.GCD Greatest Common Denominator

In [32]:
# Find the HCF of the following two numbers:
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)

3


In [33]:
# Find the GCD for all of the numbers in the following array:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4


#### 5.Summation

In [9]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
newarr = np.sum(arr1)
print(newarr)

210


In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


#### 6.Product

In [11]:
# Find the product of the elements of this array:
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [18]:
# Find the product of the elements of two arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


#### 7.Roundoff

In [39]:
# Round off 3.1666 to 2 decimal places:
arr = np.around(3.166666, 2)
print(arr)

3.17


In [40]:
arr = np.array([3.16666, 5.34444,7.33355,4.66677,8.44433])
newarr = np.around(arr, 2)
print(newarr)

[3.17 5.34 7.33 4.67 8.44]


In [41]:
arr = np.array([3.16666, 5.34444,7.33355,4.66677,8.44433])
newarr = np.around(arr, 3)
print(newarr)

[3.167 5.344 7.334 4.667 8.444]


In [42]:
arr = np.array([3.16666, 5.34444,7.33355,4.66677,8.44433])
newarr = np.around(arr, 0)
print(newarr)

[3. 5. 7. 5. 8.]


#### 8.Absolute

In [ ]:
# Return the quotient and mod:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

#### 9.Sorting

In [49]:
# Sort the array:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [50]:
# Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


## Trignoimetry Function

In [43]:
x = np.sin(np.pi/2)
print(x)

1.0


In [ ]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

In [ ]:
x = np.sinh(np.pi/2)
print(x)

## Convertion between  Degrees and Radians
- By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

In [47]:
# Degree to radian
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [48]:
# Radians to Degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


## Set Operation

In [ ]:
# Convert following array with repeated elements to a set:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

In [ ]:
# Find union of the following two set arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

In [ ]:
# Find intersection of the following two set arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

In [ ]:
# Find the difference of the set1 from set2:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

In [ ]:
# Find the symmetric difference of the set1 and set2:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)